In [2]:
import numpy as np

In [31]:
x = np.random.normal(1,1,100)
y = np.random.normal(1,2,100)
H, _, _ = np.histogram2d(x, y, bins=(10, 10))

In [13]:
result = np.where(H == np.amax(H))

In [15]:
H

array([[1., 0., 0., 0., 2., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0., 1., 0.],
       [1., 1., 2., 0., 2., 2., 0., 0., 1., 0.],
       [1., 4., 5., 4., 5., 7., 4., 0., 0., 0.],
       [1., 4., 2., 4., 2., 8., 2., 2., 0., 1.],
       [0., 1., 3., 2., 3., 4., 0., 0., 1., 1.],
       [0., 1., 0., 1., 2., 3., 2., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
result[0]

array([4])

In [22]:
alist = []
for i in range(100):
    alist.append([np.random.randn(),np.random.randn()])

In [41]:
import math

In [42]:
math.copysign(4, -1)

-4.0

In [20]:
current_angle = np.array([30,-20])
target_angle = np.array([20,-10])
update_gap = 3

updates = [[],[]]

diff_angle = target_angle - current_angle

update_n = np.ceil( np.max(np.abs(diff_angle)) / update_gap )

np.round(np.linspace(current_angle, target_angle, int(update_n)),decimals=1)

array([[ 30. , -20. ],
       [ 26.7, -16.7],
       [ 23.3, -13.3],
       [ 20. , -10. ]])