In [1]:
import numpy as np

In [31]:
x = np.random.normal(1,1,100)
y = np.random.normal(1,2,100)
H, _, _ = np.histogram2d(x, y, bins=(10, 10))

In [13]:
result = np.where(H == np.amax(H))

In [15]:
H

array([[1., 0., 0., 0., 2., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0., 1., 0.],
       [1., 1., 2., 0., 2., 2., 0., 0., 1., 0.],
       [1., 4., 5., 4., 5., 7., 4., 0., 0., 0.],
       [1., 4., 2., 4., 2., 8., 2., 2., 0., 1.],
       [0., 1., 3., 2., 3., 4., 0., 0., 1., 1.],
       [0., 1., 0., 1., 2., 3., 2., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
result[0]

array([4])

In [22]:
alist = []
for i in range(100):
    alist.append([np.random.randn(),np.random.randn()])

In [27]:
np.array(alist).T[0]

array([ 2.15463414,  0.14148903,  2.26963993, -0.45465882,  1.79676042,
        0.79905127, -0.06657295,  0.02306822, -0.68759125, -1.46093341,
        0.55735524, -0.08248686, -0.19396651, -0.38107024, -0.48563149,
       -0.54249908,  0.170364  ,  0.83713006, -0.79160521, -0.0878521 ,
        0.76339338, -1.85555043,  1.32893267, -0.97428417, -0.83025404,
        0.58201321, -0.9178971 ,  0.64886498,  0.9696183 , -1.19316059,
        0.92602063, -0.93132649,  0.39983961,  0.31353097, -0.37485924,
       -0.00381807, -0.14955398, -0.01756953,  0.38216424, -1.61415348,
       -0.26120771,  1.59032198, -1.24312419, -0.01899241, -0.50706471,
       -2.34282097, -1.48343932, -1.04162386,  0.20318909,  0.14403233,
       -1.26100437, -0.6395999 ,  0.77036993, -1.31294354,  0.76091384,
       -2.18212476,  0.22613429, -1.02752075, -0.67041701, -1.52430473,
       -0.09022586,  0.84699605, -1.3290339 , -0.2064245 , -0.1053243 ,
       -0.06587343,  1.30753764,  0.24578279, -1.40876277,  0.18